path_classifiers:
  docs:
    - README.md
    - LICENSE
extraction:
  cpp:
    prepare:
      packages:
        - gcc
        - subversion
    before_index:
      - svn export svn://svn.zabbix.com/trunk $LGTM_WORKSPACE/zabbix
      - cd $LGTM_WORKSPACE/zabbix
      - ./bootstrap
      - ./configure
      - cd -
    index:
      build_command:
        - gcc -fPIC -shared -o zaipcs.so zaipcs.c -I$LGTM_WORKSPACE/zabbix 
