language: c
compiler:
- clang
- gcc
dist: xenial
env:
- BRANCH=master
- BRANCH=release/4.4
- BRANCH=release/4.0
- BRANCH=release/3.0
before_script:
- git clone https://git.zabbix.com/scm/zbx/zabbix.git --depth 1 --single-branch --branch $BRANCH
- cd zabbix
- ./bootstrap.sh
- ./configure
- cd -
script:
- $CC -fPIC -shared -o zaipcs.so zaipcs.c -Izabbix/include
